# Generated by Django 4.2.30 on 2026-08-24 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=120)),
                ('service_type', models.CharField(max_length=100)),
                ('service_description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('address', models.TextField(blank=True, default='')),
                ('pwhash', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('plate', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('fuel_type', models.CharField(default='flex', max_length=20)),
                ('mileage', models.IntegerField(default=0)),
                ('vin', models.CharField(blank=True, default='', max_length=17)),
                ('renavam', models.CharField(blank=True, default='', max_length=11)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customer_api.customer')),
            ],
            options={
                'db_table': 'customer_vehicles',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_comment', models.TextField(blank=True, default='')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_api.appointment')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='customer_api.customer')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_api.customervehicle')),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=120)),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(max_length=120)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mechanic_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customer_api.customer')),
                ('estimate', models.ForeignKey(blank=True, db_column='estimate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_api.estimate')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_api.customervehicle')),
            ],
            options={
                'db_table': 'service_history',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('part_replaced', models.BooleanField(default=False)),
                ('part_name', models.CharField(blank=True, default='', max_length=120)),
                ('service_history', models.ForeignKey(db_column='service_history_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_api.servicehistory')),
            ],
            options={
                'db_table': 'service_history_items',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.FloatField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='customer_api.customer')),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, default='')),
                ('type', models.CharField(max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer_api.customer')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=120)),
                ('interval_km', models.IntegerField(blank=True, null=True)),
                ('interval_months', models.IntegerField(blank=True, null=True)),
                ('last_service_km', models.IntegerField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_km', models.IntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(default='ok', max_length=20)),
                ('urgency_score', models.IntegerField(default=0)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('km_remaining', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customer_api.customer')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='customer_api.customervehicle')),
            ],
            options={
                'db_table': 'maintenance_reminders',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type', models.CharField(default='peca', max_length=20)),
                ('estimate', models.ForeignKey(db_column='estimate_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_api.estimate')),
            ],
            options={
                'db_table': 'estimate_items',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'availability_slots',
                'indexes': [models.Index(fields=['date'], name='availabilit_date_d0058c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('created_at', models.FloatField()),
            ],
            options={
                'db_table': 'auth_rate_limit',
                'indexes': [models.Index(fields=['bucket', 'kind'], name='auth_rate_l_bucket_787dde_idx')],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customer_api.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_api.customervehicle'),
        ),
        migrations.CreateModel(
            name='VehicleQrLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='customer_api.customer')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='customer_api.customervehicle')),
            ],
            options={
                'db_table': 'vehicle_qr_links',
                'indexes': [models.Index(fields=['uuid'], name='vehicle_qr__uuid_e7e18a_idx'), models.Index(fields=['vehicle'], name='vehicle_qr__vehicle_e35f84_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer_api.customer')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='customer_api.customervehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'indexes': [models.Index(fields=['customer'], name='vehicle_doc_custome_6d5f3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicehistory',
            index=models.Index(fields=['customer'], name='service_his_custome_f0034c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer'], name='notificatio_custome_d0bbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereminder',
            index=models.Index(fields=['vehicle'], name='maintenance_vehicle_4af270_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['customer'], name='estimates_custome_ee3d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='customervehicle',
            index=models.Index(fields=['customer'], name='customer_ve_custome_9c996e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer'], name='appointment_custome_e82b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='appointment_date_dabb59_idx'),
        ),
    ]
