# Generated by Django 4.2.30 on 2026-08-26 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0003_mark_existing_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='customer_api.customer')),
            ],
            options={
                'db_table': 'push_subscriptions',
                'indexes': [models.Index(fields=['customer'], name='push_subscr_custome_b54a42_idx')],
            },
        ),
    ]
